[package]
name = "badproxy"
version = "0.1.0"
authors = ["raviteja <mail@raviteja.tech>"]
edition = "2018"

[dependencies]
crossbeam-channel = "0.3"
log = "0.4"
pretty_env_logger = "0.3"
tokio = {version = "0.1", features = ["async-await-preview"]}
futures = "0.1"